name: JohnWSamples
favicon: null
layout_spectrum: 0.88569
typography_spectrum: 0.69881
title: Author/Speaker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a870f'
    - '#f9f9f9'
    - '#a0a0a0'
    - '#161616'
    - '#6a6a6a'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.5684695411473513
  rhythmicContrast: 0.25
purpose: []
